-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3307
-- Generation Time: Jun 16, 2025 at 09:01 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `abc_retail`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `category_name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `banner_image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category_name`, `image`, `banner_image`) VALUES
(1, 'All Products', 'all.jpg', 'allbanner.jpg'),
(2, 'Fruits', 'fruits.jpg', 'fruitsbanner.jpg'),
(3, 'Vegetables', 'vegetables.jpg', 'vegetablesbanner.jpg'),
(4, 'Dairy', 'dairy.jpg', 'dairybanner.jpg'),
(5, 'Bakery', 'bakery.jpg', 'bakerybanner.jpg'),
(6, 'Butchery', 'butchery.jpg', 'butcherybanner.jpg'),
(7, 'Fishery', 'fishery.jpg', 'fisherybanner.jpg'),
(8, 'Household', 'household.jpg', 'householdbanner.jpg'),
(9, 'Frozen', 'frozen.jpg', 'frozenbanner.jpg'),
(10, 'Beverages', 'beverages.jpg', 'beveragesbanner.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `image` varchar(255) NOT NULL,
  `category` varchar(50) NOT NULL,
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `description`, `price`, `image`, `category`, `category_id`) VALUES
(1, 'Fresh Apples', 'Crisp and sweet apples from local farms.', 10.00, 'apple.jpg', '', 0),
(2, 'Organic Bananas', 'Naturally ripened organic bananas.', 7.50, 'banana.jpg', '', 0),
(3, 'Fresh Milk 1L', 'Pure and fresh milk, packed daily.', 5.00, 'milk.jpg', '', 0),
(4, 'Brown Bread', 'Whole grain brown bread baked fresh.', 3.50, 'bread.jpg', '', 0),
(5, 'Apple Gala', 'Discover the crisp sweetness of Apple Gala, a delightful variety from our selection! Looking for an apple with a perfect balance of sweet and tart?  Our Apple Gala offers a juicy crunch and a vibrant flavor that will tantalize your taste buds. Sourced for their exceptional quality, these apples are ideal for snacking, baking, or adding a refreshing touch to your favorite recipes. Experience the joy of a truly delicious apple with Apple Gala!', 3.50, 'fruits1.jpg', 'fruits', 2),
(6, 'Banana', 'Indulge in the creamy sweetness of our premium Bananas!  Craving a convenient and healthy snack?  Our Bananas, carefully selected for their ripeness and flavor, provide a smooth texture and satisfying sweetness. Packed with potassium and energy, they\'re the perfect choice for a quick bite, a smoothie boost, or a delicious addition to your breakfast. Elevate your everyday with the simple goodness of our Bananas.', 2.00, 'fruits2.jpg', 'fruits', 2),
(7, 'Orange Navel', 'Experience the burst of citrusy freshness with our Navel Oranges!  Looking for a juicy and vitamin C-rich treat?  Our Navel Oranges are prized for their seedless nature, easy-to-peel skin, and vibrant, sweet flavor. Whether you enjoy them fresh, squeezed into a revitalizing juice, or as a zesty addition to your culinary creations, these oranges are a taste of sunshine in every bite. Brighten your day with the exceptional quality of our Navel Oranges.', 3.20, 'fruits3.jpg', 'fruits', 2),
(8, 'Strawberries', 'Savor the sweet and succulent delight of our fresh Strawberries!  Yearning for a burst of summery flavor?  Our Strawberries, carefully chosen for their vibrant color and irresistible sweetness, offer a juicy and aromatic experience. Perfect for desserts, jams, or a healthy snack, these berries are a celebration of freshness. Treat yourself to the exquisite taste of our premium Strawberries.', 6.00, 'fruits4.jpg', 'fruits', 2),
(9, 'Blueberries', 'Discover the tiny treasures of sweetness with our delightful Blueberries!  Seeking a boost of antioxidants and a burst of flavor?  Our Blueberries, plump and juicy, deliver a sweet-tart taste sensation. Whether you sprinkle them on your cereal, blend them into smoothies, or enjoy them as a guilt-free snack, these berries are a powerhouse of nutrition and flavor. Elevate your healthy lifestyle with our exceptional Blueberries.', 7.00, 'fruits5.jpg', 'fruits', 2),
(10, 'Watermelon', 'Dive into the refreshing sweetness of our Watermelon!  Longing for the ultimate summer treat?  Our Watermelon, with its juicy and vibrant flesh, offers a cool and hydrating experience. Perfect for picnics, barbecues, or simply enjoying on a hot day, this fruit is the essence of summer refreshment. Quench your thirst and delight your taste buds with our premium Watermelon.', 9.00, 'fruits6.jpg', 'fruits', 2),
(11, 'Mango Alphonso', 'Experience the king of fruits with our exquisite Mango Alphonso!  Craving a tropical indulgence?  Our Mango Alphonso, renowned for its unparalleled sweetness and creamy texture, offers a truly luxurious taste experience. Savor the rich aroma and melt-in-your-mouth goodness of these premium Indian mangoes. Treat yourself to the royal flavor of our Mango Alphonso.', 5.50, 'fruits7.jpg', 'fruits', 2),
(12, 'Pineapple', 'Embark on a tropical flavor journey with our sweet Pineapple!  Looking for a tangy and refreshing delight?  Our Pineapples, carefully selected for their ripeness and juiciness, deliver a burst of tropical sunshine in every bite. Enjoy them fresh, grilled, or blended into your favorite beverages for a taste of paradise. Add a touch of the tropics to your day with our premium Pineapple.', 4.80, 'fruits8.jpg', 'fruits', 2),
(13, 'Kiwi', 'Uncover the vibrant and tangy zest of our fresh Kiwi!  Seeking a unique flavor and a boost of vitamin C?  Our Kiwi, with its bright green flesh and tiny black seeds, offers a delightful sweet-tart taste. Enjoy this nutritious fruit as a snack, in fruit salads, or as a colorful garnish. Elevate your fruit experience with our high-quality Kiwi.', 3.90, 'fruits9.jpg', 'fruits', 2),
(14, 'Grapes', 'Indulge in the crisp sweetness of our Seedless Green Grapes!  Looking for a light and refreshing snack?  Our Grapes, plump and juicy, deliver a burst of sweetness with every bite. Perfect for snacking, adding to fruit salads, or enjoying as a healthy treat, these grapes are a simple pleasure. Savor the freshness and quality of our Seedless Green Grapes.', 4.00, 'fruits10.jpg', 'fruits', 2),
(15, 'Papaya', 'Discover the tropical sweetness and buttery texture of our Papaya!  Craving a unique and nutritious fruit?  Our Papaya, with its vibrant color and soft flesh, offers a sweet and slightly musky flavor. Rich in vitamins and enzymes, this fruit is a delicious and healthy choice. Transport yourself to the tropics with our premium Papaya.', 3.75, 'fruits11.jpg', 'fruits', 2),
(16, 'Peach', 'Experience the juicy sweetness and delicate aroma of our Peaches!  Looking for a taste of summer?  Our Peaches, with their fuzzy skin and succulent flesh, offer a burst of sweet and tangy flavor. Enjoy them fresh, grilled, or baked into your favorite desserts for a truly delightful experience. Savor the taste of sunshine with our premium Peaches.', 5.10, 'fruits12.jpg', 'fruits', 2),
(17, 'Plum', 'Indulge in the sweet and slightly tart flavor of our Plums!  Seeking a juicy and versatile fruit?  Our Plums, with their smooth skin and vibrant colors, offer a delightful taste sensation. Enjoy them fresh, in jams, or baked into pies for a burst of fruity goodness. Discover the simple pleasure of our premium Plums.', 4.60, 'fruits13.jpg', 'fruits', 2),
(18, 'Cherry', 'Savor the sweet and irresistible taste of our fresh Cherries!  Craving a burst of juicy sweetness?  Our Cherries, with their vibrant red color and plump texture, offer a delightful flavor experience. Perfect for snacking or adding a touch of elegance to your desserts, these cherries are a true delight. Treat yourself to the exquisite taste of our premium Cherries.', 8.00, 'fruits14.jpg', 'fruits', 2),
(19, 'Coconut', 'Discover the unique flavor and versatility of our Coconut!  Looking for a taste of the tropics?  Our Coconut, with its hard shell and sweet, milky liquid, offers a distinct and satisfying experience. Enjoy the water fresh, use the flesh in your cooking, or add a tropical twist to your desserts. Explore the many possibilities of our premium Coconut.', 2.30, 'fruits15.jpg', 'fruits', 2),
(20, 'Guava', 'Experience the tropical tang and vitamin C richness of our Guava!  Seeking a unique and healthy fruit?  Our Guava, with its distinctive aroma and flavor, offers a delightful taste sensation. Enjoy it fresh, juiced, or made into jams for a burst of tropical goodness. Boost your well-being with our premium Guava.', 3.25, 'fruits16.jpg', 'fruits', 2),
(21, 'Lychee', 'Indulge in the sweet and floral fragrance of our Lychee!  Craving a delicate and exotic fruit?  Our Lychee, with its translucent flesh and unique flavor, offers a truly special taste experience. Enjoy them fresh, in fruit salads, or as a sophisticated addition to your drinks. Discover the allure of our premium Lychee.', 6.25, 'fruits17.jpg', 'fruits', 2),
(22, 'Pomegranate', 'Uncover the jewel-like sweetness of our Pomegranate!  Seeking a burst of antioxidants and a unique flavor?  Our Pomegranate, filled with juicy arils, offers a sweet-tart taste sensation. Sprinkle them on salads, enjoy them as a snack, or use them to add a touch of elegance to your dishes. Elevate your culinary experience with our premium Pomegranate.', 4.20, 'fruits18.jpg', 'fruits', 2),
(23, 'Raspberry', 'Savor the delicate sweetness and tangy twist of our Raspberries!  Looking for a burst of flavor and a touch of elegance?  Our Raspberries, with their vibrant color and soft texture, offer a delightful taste experience. Enjoy them fresh, in jams, or as a beautiful topping for your desserts. Treat yourself to the exquisite taste of our premium Raspberries.', 7.50, 'fruits19.jpg', 'fruits', 2),
(24, 'Blackberry', 'Indulge in the rich and complex flavor of our Blackberries!  Seeking a burst of antioxidants and a touch of wildness?  Our Blackberries, with their deep color and juicy texture, offer a sweet and slightly tart taste sensation. Enjoy them fresh, in pies, or as a healthy and delicious snack. Discover the intense flavor of our premium Blackberries.', 7.80, 'fruits20.jpg', 'fruits', 2),
(25, 'Carrot', 'Discover the crisp and vibrant flavor of our fresh Carrots! Looking for a versatile and healthy vegetable? Our Carrots, with their bright orange hue and sweet taste, are perfect for snacking, roasting, or adding to your favorite dishes. Packed with vitamins and fiber, they\'re a nutritious addition to any meal. Elevate your culinary creations with the quality of our fresh Carrots.', 2.10, 'vegetables1.jpg', 'vegetables', 3),
(26, 'Broccoli', 'Indulge in the wholesome goodness of our green Broccoli! Seeking a nutritious and versatile vegetable? Our Broccoli, with its tender florets and mild flavor, is a powerhouse of vitamins and antioxidants. Enjoy it steamed, roasted, or added to stir-fries for a healthy and delicious meal. Enhance your well-being with our premium Broccoli.', 3.50, 'vegetables2.jpg', 'vegetables', 3),
(27, 'Spinach', 'Experience the fresh and leafy goodness of our Spinach! Looking for a nutrient-rich vegetable to boost your health? Our Spinach, with its vibrant green leaves and delicate flavor, is packed with vitamins and minerals. Enjoy it raw in salads, sautéed as a side dish, or blended into smoothies for a nutritious boost. Discover the versatility of our fresh Spinach.', 2.90, 'vegetables3.jpg', 'vegetables', 3),
(28, 'Lettuce', 'Discover the crisp and refreshing crunch of our Lettuce! Seeking the perfect base for your salads and wraps? Our Lettuce, with its crisp leaves and mild flavor, provides a refreshing and hydrating addition to any meal. Enjoy it fresh in salads, use it for wraps, or add it to sandwiches for a satisfying crunch. Elevate your salads with our premium Lettuce.', 1.80, 'vegetables4.jpg', 'vegetables', 3),
(29, 'Tomato', 'Savor the juicy and vibrant flavor of our vine-ripened Tomatoes! Looking for a versatile and flavorful addition to your cooking? Our Tomatoes, with their rich red color and sweet-tangy taste, are perfect for salads, sauces, or enjoying fresh off the vine. Add a burst of freshness to your meals with our premium Tomatoes.', 2.60, 'vegetables5.jpg', 'vegetables', 3),
(30, 'Potato', 'Indulge in the earthy goodness of our golden Potatoes! Seeking a versatile and satisfying staple? Our Potatoes, with their smooth skin and creamy texture, are perfect for baking, mashing, frying, or roasting. Enjoy them as a side dish, a main ingredient, or a comforting snack. Discover the endless possibilities of our premium Potatoes.', 2.20, 'vegetables6.jpg', 'vegetables', 3),
(31, 'Onion', 'Experience the bold and pungent flavor of our Onions! Looking for an essential ingredient to enhance your culinary creations? Our Onions, with their layers of flavor and aromatic essence, are a staple in kitchens worldwide. Use them to add depth to sauces, stir-fries, soups, and more. Elevate your dishes with the distinctive flavor of our premium Onions.', 1.75, 'vegetables7.jpg', 'vegetables', 3),
(32, 'Cucumber', 'Discover the cool and refreshing crispness of our Cucumbers! Seeking a hydrating and light addition to your meals? Our Cucumbers, with their smooth green skin and mild flavor, are perfect for salads, sandwiches, or enjoying as a refreshing snack. Stay cool and refreshed with our premium Cucumbers.', 1.50, 'vegetables8.jpg', 'vegetables', 3),
(33, 'Bell Pepper', 'Savor the vibrant colors and flavors of our mixed Bell Peppers! Looking for a sweet and crunchy addition to your dishes? Our Bell Peppers, in a variety of colors, offer a range of sweet and slightly tangy flavors. Enjoy them raw in salads, sautéed in stir-fries, or roasted for a delicious side dish. Add a pop of color and flavor to your meals with our premium Bell Peppers.', 3.70, 'vegetables9.jpg', 'vegetables', 3),
(34, 'Zucchini', 'Indulge in the tender and mild flavor of our green Zucchini! Seeking a versatile and healthy vegetable? Our Zucchini, with its smooth skin and delicate taste, is perfect for grilling, roasting, or adding to pasta dishes. Enjoy its tender texture and subtle sweetness in your favorite recipes. Discover the versatility of our premium Zucchini.', 2.60, 'vegetables10.jpg', 'vegetables', 3),
(35, 'Celery', 'Experience the crisp and refreshing texture of our fresh Celery! Looking for a low-calorie and hydrating snack? Our Celery, with its crunchy stalks and mild flavor, is perfect for snacking, adding to salads, or using as a flavorful ingredient in soups and stews. Enjoy the refreshing crunch of our premium Celery.', 1.95, 'vegetables11.jpg', 'vegetables', 3),
(36, 'Garlic', 'Discover the pungent and aromatic flavor of our whole Garlic bulbs! Seeking an essential ingredient to elevate your cooking? Our Garlic, with its distinct flavor and aroma, is a staple in kitchens worldwide. Use it to add depth to sauces, stir-fries, roasts, and more. Enhance your dishes with the bold flavor of our premium Garlic.', 2.30, 'vegetables12.jpg', 'vegetables', 3),
(37, 'Cauliflower', 'Indulge in the mild and nutty flavor of our white Cauliflower head! Looking for a versatile and healthy vegetable? Our Cauliflower, with its creamy white florets and tender texture, is perfect for roasting, steaming, or mashing. Enjoy its mild flavor and creamy texture in your favorite recipes. Discover the versatility of our premium Cauliflower.', 3.40, 'vegetables13.jpg', 'vegetables', 3),
(38, 'Pumpkin', 'Experience the sweet and earthy flavor of our whole cooking Pumpkin! Looking for a seasonal and versatile vegetable? Our Pumpkin, with its vibrant orange color and rich flavor, is perfect for pies, soups, stews, and more. Enjoy the warmth and comfort of pumpkin in your favorite dishes. Savor the seasonal goodness of our premium Pumpkin.', 4.50, 'vegetables14.jpg', 'vegetables', 3),
(39, 'Sweet Corn', 'Discover the sweet and juicy kernels of our yellow Sweet Corn cobs! Seeking a taste of summer sweetness? Our Sweet Corn, with its tender kernels and vibrant flavor, is perfect for grilling, boiling, or adding to salads and side dishes. Enjoy the sweet and satisfying taste of our premium Sweet Corn.', 3.10, 'vegetables15.jpg', 'vegetables', 3),
(40, 'Green Beans', 'Indulge in the crisp and tender texture of our fresh Green Beans! Looking for a healthy and versatile vegetable? Our Green Beans, with their vibrant green color and delicate flavor, are perfect for steaming, sautéing, or adding to casseroles. Enjoy their crisp texture and fresh taste in your favorite recipes. Elevate your meals with our premium Green Beans.', 2.80, 'vegetables16.jpg', 'vegetables', 3),
(41, 'Beetroot', 'Experience the earthy sweetness and vibrant color of our dark red Beets! Looking for a nutritious and colorful addition to your meals? Our Beets, with their rich red hue and sweet flavor, are perfect for roasting, pickling, or adding to salads. Enjoy their unique flavor and vibrant color in your favorite dishes. Discover the earthy goodness of our premium Beets.', 2.70, 'vegetables17.jpg', 'vegetables', 3),
(42, 'Radish', 'Discover the crisp and peppery flavor of our white Radish bunch! Seeking a zesty and refreshing addition to your salads? Our Radish, with its crisp texture and slightly spicy flavor, adds a delightful zing to any dish. Enjoy them raw in salads, pickled for a tangy treat, or as a colorful garnish. Add a touch of zest to your meals with our premium Radish.', 1.90, 'vegetables18.jpg', 'vegetables', 3),
(43, 'Eggplant', 'Indulge in the glossy and tender texture of our purple Eggplant! Looking for a versatile and flavorful vegetable? Our Eggplant, with its smooth skin and meaty texture, is perfect for grilling, baking, or adding to stews and curries. Enjoy its unique flavor and versatility in your favorite recipes. Discover the culinary possibilities of our premium Eggplant.', 3.20, 'vegetables19.jpg', 'vegetables', 3),
(44, 'Okra', 'Experience the unique and tender texture of our green Okra fingers! Looking for a flavorful and nutritious addition to your cooking? Our Okra, with its distinctive shape and mild flavor, is perfect for soups, stews, and stir-fries. Enjoy its tender texture and subtle flavor in your favorite dishes. Explore the culinary delights of our premium Okra.', 2.95, 'vegetables20.jpg', 'vegetables', 3),
(45, 'Whole Milk', 'Indulge in the creamy richness of our Fresh Whole Milk 1L! Looking for pure and wholesome dairy goodness? Our Whole Milk, packed fresh daily, provides a rich and satisfying taste. Enjoy it on its own, with cereal, or in your favorite recipes. Experience the pure delight of our premium Fresh Whole Milk.', 3.25, 'dairy1.jpg', 'dairy', 4),
(46, 'Skimmed Milk', 'Discover the light and refreshing taste of our Skimmed Milk 1L! Seeking a low-fat and healthy dairy option? Our Skimmed Milk delivers the same essential nutrients as whole milk, with less fat and calories. Enjoy it as a light beverage, with cereal, or in your healthy recipes. Choose the healthy goodness of our premium Skimmed Milk.', 3.00, 'dairy2.jpg', 'dairy', 4),
(47, 'Cheddar Cheese', 'Savor the rich and mature flavor of our Cheddar Cheese block! Looking for a cheese with a bold and tangy taste? Our Cheddar Cheese, aged to perfection, offers a firm texture and a sharp, satisfying flavor. Enjoy it in sandwiches, on crackers, or melted into your favorite dishes. Elevate your cheese experience with our premium Cheddar Cheese.', 5.20, 'dairy3.jpg', 'dairy', 4),
(48, 'Mozzarella Cheese', 'Indulge in the smooth and creamy texture of our Mozzarella Cheese 250g! Seeking the perfect cheese for your pizzas and pastas? Our Mozzarella Cheese, with its mild flavor and excellent melting properties, is ideal for creating delicious Italian dishes. Enjoy its creamy goodness in your favorite recipes. Create culinary masterpieces with our premium Mozzarella Cheese.', 4.80, 'dairy4.jpg', 'dairy', 4),
(49, 'Yogurt Plain', 'Experience the simple and tangy goodness of our Yogurt Plain 500g! Looking for a versatile and healthy dairy option? Our Plain Yogurt, with its smooth texture and slightly tart flavor, is perfect for breakfast, snacks, or adding a creamy touch to your recipes. Enjoy its natural goodness on its own or with your favorite toppings. Discover the versatility of our premium Plain Yogurt.', 2.50, 'dairy5.jpg', 'dairy', 4),
(50, 'Greek Yogurt', 'Savor the rich and creamy texture of our Greek Yogurt! Seeking a high-protein and satisfying dairy delight? Our Greek Yogurt, with its thick and velvety texture, is packed with protein and offers a tangy and delicious flavor. Enjoy it as a healthy breakfast, snack, or dessert. Elevate your yogurt experience with our premium Greek Yogurt.', 3.60, 'dairy6.jpg', 'dairy', 4),
(51, 'Butter Unsalted', 'Indulge in the pure and creamy taste of our Butter Unsalted 250g! Looking for the perfect butter for your baking and cooking? Our Unsalted Butter, made from the finest cream, provides a rich and delicate flavor. Use it in your favorite recipes or spread it on toast for a simple delight. Experience the quality of our premium Unsalted Butter.', 4.10, 'dairy7.jpg', 'dairy', 4),
(52, 'Butter Salted', 'Experience the rich and savory taste of our Salted Butter stick! Seeking the perfect butter for your table? Our Salted Butter, made from the finest cream, offers a creamy texture and a balanced salty flavor. Enjoy it on bread, rolls, or use it to enhance the flavor of your dishes. Savor the deliciousness of our premium Salted Butter.', 4.15, 'dairy8.jpg', 'dairy', 4),
(53, 'Cream Cheese', 'Discover the smooth and creamy delight of our Cream Cheese! Looking for a versatile and flavorful cheese spread? Our Cream Cheese, with its velvety texture and mild tangy flavor, is perfect for bagels, sandwiches, or adding creaminess to your desserts. Enjoy its smooth and delicious goodness. Elevate your spreads with our premium Cream Cheese.', 3.95, 'dairy9.jpg', 'dairy', 4),
(54, 'Cottage Cheese', 'Savor the light and fresh taste of our Cottage Cheese! Seeking a low-fat and high-protein dairy option? Our Cottage Cheese, with its creamy texture and mild flavor, is perfect for a healthy snack, breakfast, or as a topping for your favorite dishes. Enjoy its wholesome goodness. Choose the healthy delight of our premium Cottage Cheese.', 4.30, 'dairy10.jpg', 'dairy', 4),
(55, 'Flavored Yogurt', 'Indulge in the sweet and fruity delight of our Flavored Yogurt cup! Looking for a convenient and delicious yogurt treat? Our Flavored Yogurt, with its creamy texture and burst of strawberry flavor, is perfect for a quick snack or a light dessert. Enjoy the sweet and fruity goodness. Treat yourself to our premium Flavored Yogurt.', 1.80, 'dairy11.jpg', 'dairy', 4),
(56, 'Milk Powder', 'Discover the convenience and versatility of our Milk Powder 1kg! Seeking a long-lasting and easy-to-use milk option? Our Milk Powder, made from high-quality milk, can be reconstituted to create fresh milk whenever you need it. Use it for baking, cooking, or enjoying a glass of milk. Experience the convenience of our premium Milk Powder.', 8.50, 'dairy12.jpg', 'dairy', 4),
(57, 'Evaporated Milk', 'Savor the rich and creamy sweetness of our Evaporated Milk! Looking for a concentrated milk option for your recipes? Our Evaporated Milk, with its smooth texture and rich flavor, is perfect for desserts, sauces, and beverages. Add a touch of creamy sweetness to your dishes with our premium Evaporated Milk.', 2.20, 'dairy13.jpg', 'dairy', 4),
(58, 'Condensed Milk', 'Indulge in the thick and sweet richness of our Condensed Milk! Seeking a decadent and sweet milk option? Our Condensed Milk, with its thick texture and intense sweetness, is perfect for desserts, coffee, and other treats. Add a touch of sweetness and richness to your creations with our premium Condensed Milk.', 2.60, 'dairy14.jpg', 'dairy', 4),
(59, 'Cream', 'Experience the smooth and velvety texture of our Cream 250ml! Looking for the perfect cream for your cooking and desserts? Our Cream, with its rich and creamy texture, is ideal for sauces, soups, and adding a touch of luxury to your desserts. Elevate your culinary creations with our premium Cream.', 3.70, 'dairy15.jpg', 'dairy', 4),
(60, 'Flavored Milk', 'Savor the rich and chocolatey delight of our Flavored Milk! Looking for a delicious and convenient milk treat? Our Flavored Milk, with its creamy texture and chocolate flavor, is perfect for a quick snack or a tasty beverage. Enjoy the classic combination of milk and chocolate. Treat yourself to our premium Flavored Milk.', 2.90, 'dairy16.jpg', 'dairy', 4),
(61, 'Goat Cheese', 'Discover the tangy and distinct flavor of our Imported Goat Cheese! Seeking a unique and flavorful cheese option? Our Goat Cheese, with its creamy texture and tangy taste, is perfect for salads, appetizers, or enjoying with crackers. Experience the unique taste of our premium Goat Cheese.', 6.80, 'dairy17.jpg', 'dairy', 4),
(62, 'Paneer', 'Indulge in the fresh and mild flavor of our Indian Paneer! Looking for a versatile and protein-rich cheese? Our Paneer, with its firm texture and mild taste, is perfect for curries, stir-fries, and other Indian dishes. Enjoy its fresh and wholesome goodness. Discover the culinary possibilities of our premium Paneer.', 4.50, 'dairy18.jpg', 'dairy', 4),
(63, 'Lassi', 'Experience the refreshing and traditional taste of our Indian Lassi! Seeking a cooling and flavorful yogurt drink? Our Lassi, with its creamy texture and blend of yogurt and spices, is perfect for a refreshing beverage. Enjoy its traditional flavors and cooling properties. Quench your thirst with our premium Lassi.', 3.30, 'dairy19.jpg', 'dairy', 4),
(64, 'Kefir', 'Discover the tangy and probiotic goodness of our Fermented Milk Drink Kefir! Looking for a healthy and refreshing beverage? Our Kefir, with its creamy texture and slightly tart flavor, is packed with probiotics and nutrients. Enjoy it as a healthy drink or add it to your smoothies. Boost your well-being with our premium Kefir.', 3.85, 'dairy20.jpg', 'dairy', 4),
(65, 'White Bread', 'Indulge in the soft and classic taste of our Sliced White Sandwich Bread! Looking for the perfect bread for your everyday sandwiches? Our White Bread, with its soft texture and mild flavor, is a versatile choice for any meal. Enjoy its simple goodness and create delicious sandwiches with our premium White Bread.', 2.50, 'bakery1.jpg', 'bakery', 5),
(66, 'Whole Wheat Bread', 'Discover the wholesome goodness of our Healthy Whole Wheat Loaf! Seeking a nutritious and flavorful bread option? Our Whole Wheat Bread, made with whole grains, offers a rich and nutty flavor. Enjoy it toasted, in sandwiches, or as a healthy side to your meals. Choose the healthy delight of our premium Whole Wheat Bread.', 2.80, 'bakery2.jpg', 'bakery', 5),
(67, 'Baguette', 'Savor the crispy crust and soft interior of our Fresh French Baguette! Looking for the perfect bread for your French-inspired meals? Our Baguette, with its long and slender shape, offers a delightful combination of textures and flavors. Enjoy it with soups, salads, or as a side to your favorite dishes. Experience the authentic taste of our premium French Baguette.', 3.00, 'bakery3.jpg', 'bakery', 5),
(68, 'Croissant', 'Indulge in the buttery and flaky layers of our buttery Croissants! Seeking a classic and delicious pastry? Our Croissants, made with rich butter and delicate dough, offer a melt-in-your-mouth experience. Enjoy them for breakfast, brunch, or a special treat. Treat yourself to the exquisite taste of our premium Croissants.', 2.75, 'bakery4.jpg', 'bakery', 5),
(69, 'Donut', 'Discover the sweet and delightful indulgence of our Chocolate Glazed Donut! Looking for a classic and irresistible treat? Our Donut, with its soft texture and rich chocolate glaze, is perfect for a sweet snack or a moment of indulgence. Enjoy the classic flavor of our premium Donut.', 1.50, 'bakery5.jpg', 'bakery', 5),
(70, 'Bagel', 'Savor the chewy and satisfying texture of our New York Style Bagel! Seeking a hearty and flavorful breakfast option? Our Bagel, with its dense texture and classic shape, is perfect for toasting and topping with your favorite spreads. Enjoy its authentic taste and satisfying chewiness. Start your day right with our premium Bagel.', 1.80, 'bakery6.jpg', 'bakery', 5),
(71, 'Muffin', 'Indulge in the moist and flavorful goodness of our Blueberry Muffin! Looking for a sweet and fruity treat? Our Muffin, bursting with juicy blueberries, offers a delightful combination of flavors and textures. Enjoy it for breakfast, a snack, or a sweet indulgence. Savor the deliciousness of our premium Blueberry Muffin.', 2.25, 'bakery7.jpg', 'bakery', 5),
(72, 'Cupcake', 'Experience the sweet and festive delight of our Vanilla Frosted Cupcake! Seeking a classic and celebratory treat? Our Cupcake, with its moist cake and creamy vanilla frosting, is perfect for parties, birthdays, or a simple moment of joy. Enjoy the classic flavor and festive spirit of our premium Cupcake.', 2.40, 'bakery8.jpg', 'bakery', 5),
(73, 'Chocolate Cake', 'Savor the rich and decadent indulgence of our Chocolate Cake slice! Looking for a truly satisfying dessert? Our Chocolate Cake, with its moist layers and rich chocolate frosting, is a chocolate lover\'s dream. Treat yourself to a slice of pure decadence. Experience the ultimate chocolate delight with our premium Chocolate Cake.', 4.50, 'bakery9.jpg', 'bakery', 5),
(74, 'Pita Bread', 'Discover the soft and versatile goodness of our Pita Bread pack! Seeking the perfect bread for your Mediterranean-inspired meals? Our Pita Bread, with its soft and pliable texture, is ideal for filling with your favorite ingredients. Enjoy it for sandwiches, wraps, or dipping. Explore the culinary possibilities of our premium Pita Bread.', 3.20, 'bakery10.jpg', 'bakery', 5),
(75, 'Flatbread', 'Indulge in the soft and warm comfort of our Flatbread! Looking for a versatile and flavorful bread option? Our Flatbread, with its soft texture and subtle flavor, is perfect for wraps, pizzas, or enjoying as a side to your meals. Enjoy its simple goodness and create delicious dishes with our premium Flatbread.', 2.90, 'bakery11.jpg', 'bakery', 5),
(76, 'Garlic Bread', 'Experience the savory and aromatic delight of our Garlic Bread! Seeking the perfect accompaniment to your Italian dishes? Our Garlic Bread, with its crispy crust and buttery garlic flavor, is a classic favorite. Enjoy it with pasta, salads, or as a delicious appetizer. Enhance your meals with the irresistible flavor of our premium Garlic Bread.', 3.60, 'bakery12.jpg', 'bakery', 5),
(77, 'Brownie', 'Savor the rich and fudgy indulgence of our Chocolate Brownie! Looking for a decadent and satisfying treat? Our Brownie, with its moist and chewy texture, is a chocolate lover\'s delight. Enjoy it warm or cold for a truly delightful experience. Treat yourself to the ultimate chocolate satisfaction with our premium Brownie.', 2.80, 'bakery13.jpg', 'bakery', 5),
(78, 'Tart', 'Discover the delicate sweetness and fruity elegance of our Mini Fruit Tart! Seeking a sophisticated and delightful dessert? Our Fruit Tart, with its buttery crust and fresh fruit topping, is a perfect choice for any occasion. Enjoy its delicate flavors and beautiful presentation. Elevate your dessert experience with our premium Fruit Tart.', 3.50, 'bakery14.jpg', 'bakery', 5),
(79, 'Pastry', 'Indulge in the flaky and sweet goodness of our Apple Pastry! Looking for a delightful and comforting treat? Our Pastry, filled with sweet apples and encased in a flaky crust, is a perfect choice for breakfast or a sweet snack. Enjoy its warm and comforting flavors. Savor the deliciousness of our premium Apple Pastry.', 2.95, 'bakery15.jpg', 'bakery', 5),
(80, 'Rye Bread', 'Experience the hearty and distinctive flavor of our Rye Bread! Seeking a traditional and flavorful bread option? Our Rye Bread, with its dense texture and earthy taste, is perfect for sandwiches or enjoying with your favorite spreads. Discover the unique taste of our premium Rye Bread.', 3.10, 'bakery16.jpg', 'bakery', 5),
(81, 'Breadsticks', 'Savor the crispy and savory delight of our Italian Breadsticks! Looking for the perfect accompaniment to your soups and salads? Our Breadsticks, with their crunchy texture and subtle flavor, are a classic choice. Enjoy them as a snack or as a side to your favorite dishes. Add a touch of Italian flair to your meals with our premium Breadsticks.', 2.60, 'bakery17.jpg', 'bakery', 5),
(82, 'Sweet Roll', 'Indulge in the warm and sweet cinnamon swirl of our Sweet Roll! Seeking a comforting and delicious breakfast or treat? Our Sweet Roll, with its soft dough and sweet cinnamon filling, is a classic indulgence. Enjoy its warm and gooey goodness. Treat yourself to the sweet delight of our premium Sweet Roll.', 2.85, 'bakery18.jpg', 'bakery', 5),
(83, 'Sourdough Bread', 'Discover the tangy and rustic charm of our Sourdough Bread! Looking for an artisan bread with a unique flavor? Our Sourdough Bread, with its chewy texture and slightly sour taste, is perfect for sandwiches, toast, or enjoying with your favorite dips. Experience the authentic taste of our premium Sourdough Bread.', 4.00, 'bakery19.jpg', 'bakery', 5),
(84, 'Danish', 'Savor the sweet and creamy indulgence of our Cheese Danish! Seeking a flaky and flavorful pastry? Our Danish, filled with creamy cheese and encased in a buttery pastry, is a perfect choice for breakfast or a special treat. Enjoy its rich and satisfying flavors. Treat yourself to the exquisite taste of our premium Cheese Danish.', 3.75, 'bakery20.jpg', 'bakery', 5),
(85, 'Beef Mince', 'Indulge in the lean and versatile goodness of our Beef Mince 500g! Looking for a high-quality ground beef for your culinary creations? Our Beef Mince, with its fine texture and rich flavor, is perfect for burgers, sauces, and countless other dishes. Create delicious and satisfying meals with our premium Beef Mince.', 6.50, 'butchery1.jpg', 'butchery', 6),
(86, 'Chicken Breast', 'Discover the tender and healthy delight of our Chicken Breast 500g! Seeking a lean and protein-rich option? Our Chicken Breast, boneless and skinless, is incredibly versatile for grilling, baking, or stir-frying. Enjoy its delicate flavor and create nutritious meals with our premium Chicken Breast.', 5.20, 'butchery2.jpg', 'butchery', 6),
(87, 'Lamb Chops', 'Savor the rich and flavorful experience of our Lamb Chops! Looking for a premium cut for a special occasion? Our Lamb Chops, tender and juicy, offer a distinctive and delicious taste. Grill, pan-sear, or roast them to perfection for an unforgettable dining experience. Treat yourself to the exquisite quality of our Lamb Chops.', 8.90, 'butchery3.jpg', 'butchery', 6),
(88, 'Whole Chicken', 'Experience the wholesome goodness of our Whole Chicken! Seeking a versatile and satisfying centerpiece for your meals? Our Whole Chicken, fresh and plump, is perfect for roasting, baking, or grilling. Enjoy its succulent flavor and create hearty dishes for the whole family with our premium Whole Chicken.', 9.50, 'butchery4.jpg', 'butchery', 6),
(89, 'Steak Ribeye', 'Indulge in the premium quality of our Steak Ribeye! Looking for a truly exceptional cut of beef? Our Ribeye Steak, known for its marbling and tenderness, offers a rich and flavorful experience. Grill or pan-sear it to your desired level of perfection for a memorable meal. Elevate your dining experience with our premium Ribeye Steak.', 12.00, 'butchery5.jpg', 'butchery', 6),
(90, 'Beef Sausage', 'Discover the savory and satisfying taste of our Beef Sausage! Seeking a flavorful addition to your barbecues or meals? Our Beef Sausage, seasoned to perfection, offers a juicy and delicious experience. Grill, pan-fry, or add them to your favorite recipes for a burst of flavor. Enjoy the quality and taste of our premium Beef Sausage.', 5.60, 'butchery6.jpg', 'butchery', 6),
(91, 'Chicken Thighs', 'Savor the tender and flavorful delight of our Chicken Thighs 500g! Looking for a juicy and versatile cut of chicken? Our Chicken Thighs, boneless and skinless, are perfect for grilling, baking, or adding to stews and curries. Enjoy their rich flavor and create delicious meals with our premium Chicken Thighs.', 4.80, 'butchery7.jpg', 'butchery', 6),
(92, 'Turkey Breast', 'Indulge in the lean and delicate flavor of our Turkey Breast slices! Seeking a healthy and convenient option for sandwiches or salads? Our Turkey Breast, thinly sliced and ready-to-eat, offers a mild and satisfying taste. Create delicious and nutritious meals with our premium Turkey Breast.', 5.90, 'butchery8.jpg', 'butchery', 6),
(93, 'Duck Breast', 'Experience the rich and flavorful indulgence of our Duck Breast! Looking for a gourmet option for a special dinner? Our Duck Breast, tender and succulent, offers a distinctive and delicious taste. Pan-sear or roast it to perfection for an elegant dining experience. Treat yourself to the culinary delight of our premium Duck Breast.', 10.50, 'butchery9.jpg', 'butchery', 6),
(94, 'Chicken Wings', 'Savor the spicy and savory kick of our Chicken Wings BBQ! Seeking a flavorful and fun appetizer or snack? Our Chicken Wings, marinated and ready to cook, offer a delicious BBQ flavor. Bake, grill, or fry them for a crowd-pleasing treat. Enjoy the bold taste of our premium Chicken Wings.', 4.60, 'butchery10.jpg', 'butchery', 6),
(95, 'Beef Burger', 'Discover the juicy and satisfying goodness of our Beef Burger patties! Looking for the perfect patties for your homemade burgers? Our Beef Burger patties, made from high-quality beef, offer a rich and flavorful experience. Grill or pan-fry them to your desired level of doneness for a classic American meal. Create delicious burgers with our premium Beef Burger patties.', 7.00, 'butchery11.jpg', 'butchery', 6),
(96, 'Mutton Curry Cut', 'Indulge in the rich and flavorful taste of our Mutton Curry Cut! Seeking the perfect meat for your Indian curries and stews? Our Mutton Curry Cut, bone-in and tender, offers a distinctive and delicious flavor. Slow-cook it to perfection for a truly authentic culinary experience. Savor the taste of tradition with our premium Mutton Curry Cut.', 9.20, 'butchery12.jpg', 'butchery', 6),
(97, 'Pork Chops', 'Experience the tender and flavorful delight of our Pork Chops! Looking for a versatile and satisfying meat option? Our Pork Chops, juicy and lean, are perfect for grilling, baking, or pan-searing. Enjoy their mild flavor and create delicious meals with our premium Pork Chops.', 8.00, 'butchery13.jpg', 'butchery', 6),
(98, 'Salami', 'Savor the rich and savory flavor of our Italian Dry Salami! Seeking a flavorful addition to your charcuterie boards or sandwiches? Our Salami, cured to perfection, offers a bold and distinctive taste. Enjoy it sliced thin for a delicious appetizer or snack. Experience the authentic taste of our premium Salami.', 5.40, 'butchery14.jpg', 'butchery', 6),
(99, 'Ham', 'Indulge in the sweet and savory delight of our Honey Glazed Ham slices! Looking for a delicious and convenient option for sandwiches or salads? Our Ham, thinly sliced and glazed with honey, offers a sweet and savory flavor. Create delicious and satisfying meals with our premium Honey Glazed Ham.', 4.70, 'butchery15.jpg', 'butchery', 6),
(100, 'Sliced Chicken', 'Discover the lean and flavorful goodness of our Grilled Chicken Slices! Seeking a healthy and convenient protein option? Our Chicken Slices, grilled to perfection, are perfect for salads, wraps, or adding to your favorite dishes. Enjoy their smoky flavor and create nutritious meals with our premium Grilled Chicken Slices.', 5.10, 'butchery16.jpg', 'butchery', 6),
(101, 'Brisket', 'Experience the tender and flavorful indulgence of our Slow Cooked Beef Brisket! Looking for a hearty and satisfying meal? Our Beef Brisket, slow-cooked to perfection, offers a rich and melt-in-your-mouth experience. Shred it for sandwiches, tacos, or enjoy it as a main course. Savor the deliciousness of our premium Beef Brisket.', 11.00, 'butchery17.jpg', 'butchery', 6),
(102, 'Chicken Nuggets', 'Savor the crispy and convenient delight of our Frozen Chicken Nuggets! Seeking a quick and easy meal option for kids and adults alike? Our Chicken Nuggets, made from high-quality chicken, are perfect for baking or frying. Enjoy their crispy coating and tender interior for a satisfying snack or meal. Enjoy the convenience of our premium Chicken Nuggets.', 4.50, 'butchery18.jpg', 'butchery', 6),
(103, 'Ground Turkey', 'Indulge in the lean and flavorful goodness of our Ground Turkey! Looking for a healthy and versatile alternative to ground beef? Our Ground Turkey, with its fine texture and mild flavor, is perfect for burgers, sauces, and countless other dishes. Create delicious and nutritious meals with our premium Ground Turkey.', 5.75, 'butchery19.jpg', 'butchery', 6),
(104, 'Veal Cutlet', 'Discover the tender and flavorful experience of our Breaded Veal Cutlet! Seeking a classic and elegant meat option? Our Veal Cutlet, breaded and ready to cook, offers a delicate and delicious taste. Pan-fry it to golden perfection for a sophisticated meal. Elevate your dining experience with our premium Veal Cutlet.', 10.20, 'butchery20.jpg', 'butchery', 6),
(105, 'Salmon Fillet', 'Indulge in the fresh and delicate flavor of our Atlantic Salmon Fillet! Looking for a healthy and delicious seafood option? Our Salmon Fillet, rich in omega-3 fatty acids, offers a tender texture and a vibrant taste. Grill, bake, or pan-sear it for a gourmet meal. Experience the premium quality of our Atlantic Salmon.', 12.50, 'fishery1.jpg', 'fishery', 7),
(106, 'Tilapia', 'Discover the mild and flaky goodness of our whole cleaned Tilapia! Seeking a versatile and affordable fish option? Our Tilapia, cleaned and ready to cook, offers a delicate flavor that pairs well with various seasonings and cooking methods. Bake, fry, or grill it for a healthy and satisfying meal. Enjoy the fresh taste of our premium Tilapia.', 6.20, 'fishery2.jpg', 'fishery', 7),
(107, 'Shrimp', 'Savor the sweet and succulent delight of our Peeled Frozen Shrimp! Looking for a convenient and versatile seafood ingredient? Our Shrimp, peeled and frozen for freshness, are perfect for stir-fries, pasta dishes, or grilling. Enjoy their tender texture and delicious flavor in your favorite recipes. Add a touch of elegance to your meals with our premium Shrimp.', 9.00, 'fishery3.jpg', 'fishery', 7),
(108, 'Tuna Steak', 'Experience the rich and flavorful indulgence of our Tuna Steak cuts! Seeking a premium and meaty fish option? Our Tuna Steak, known for its firm texture and bold taste, is perfect for grilling or searing. Enjoy its exquisite flavor and create a gourmet seafood experience with our premium Tuna Steak.', 10.80, 'fishery4.jpg', 'fishery', 7),
(109, 'Sardines', 'Discover the bold and savory flavor of our Canned Sardines in Olive Oil! Looking for a convenient and nutritious pantry staple? Our Sardines, packed in olive oil, offer a rich source of omega-3 fatty acids and protein. Enjoy them on toast, in salads, or as a flavorful snack. Savor the taste of the sea with our premium Sardines.', 2.90, 'fishery5.jpg', 'fishery', 7),
(110, 'Cod Fillet', 'Indulge in the delicate and flaky texture of our Boneless Cod Fillet! Seeking a mild and versatile fish option? Our Cod Fillet, boneless and ready to cook, offers a tender and delicious taste. Bake, fry, or poach it for a healthy and satisfying meal. Enjoy the pure and fresh flavor of our premium Cod.', 8.40, 'fishery6.jpg', 'fishery', 7),
(111, 'Crab Meat', 'Savor the sweet and delicate meat of our Ready-to-Eat Crab! Looking for a luxurious and convenient seafood treat? Our Crab Meat, cooked and ready to enjoy, offers a tender and flavorful experience. Use it in salads, dips, or pasta dishes for a touch of elegance. Treat yourself to the exquisite taste of our premium Crab.', 11.00, 'fishery7.jpg', 'fishery', 7),
(112, 'Lobster Tail', 'Experience the rich and decadent flavor of our Frozen Lobster Tails! Seeking a gourmet seafood indulgence? Our Lobster Tails, frozen for freshness, offer a succulent and tender meat. Broil or bake them for a truly special occasion. Elevate your dining experience with the luxurious taste of our premium Lobster Tails.', 15.00, 'fishery8.jpg', 'fishery', 7),
(113, 'Oysters', 'Discover the briny and delicate flavor of our fresh Oysters! Looking for a unique and sophisticated seafood delicacy? Our Oysters, harvested fresh, offer a distinct taste of the sea. Enjoy them raw on the half shell or cooked in your favorite recipes for a truly memorable culinary experience. Savor the freshness of our premium Oysters.', 14.00, 'fishery9.jpg', 'fishery', 7),
(114, 'Clams', 'Indulge in the sweet and tender meat of our whole live Clams! Seeking a flavorful and versatile shellfish option? Our Clams, fresh and ready to cook, offer a delicate and delicious taste. Steam them in white wine, add them to pasta dishes, or create a flavorful seafood stew. Experience the freshness of the sea with our premium Clams.', 8.90, 'fishery10.jpg', 'fishery', 7),
(115, 'Smoked Salmon', 'Savor the smoky and delicate flavor of our Sliced Smoked Salmon! Looking for a gourmet addition to your breakfast or appetizers? Our Smoked Salmon, thinly sliced and ready to eat, offers a rich and flavorful experience. Enjoy it on bagels, with cream cheese, or in salads for a touch of elegance. Elevate your meals with the premium quality of our Smoked Salmon.', 11.20, 'fishery11.jpg', 'fishery', 7),
(116, 'Anchovies', 'Discover the salty and intense flavor of our Salted Anchovies in a Jar! Looking for a flavorful ingredient to enhance your sauces and dishes? Our Anchovies, preserved in salt, offer a bold and distinctive taste. Use them sparingly to add depth to your culinary creations. Experience the unique flavor of our premium Anchovies.', 3.80, 'fishery12.jpg', 'fishery', 7),
(117, 'Fish Fingers', 'Indulge in the crispy and convenient delight of our Frozen Fish Sticks! Seeking a quick and easy meal option for kids and adults alike? Our Fish Sticks, made from high-quality fish, offer a crispy coating and a tender interior. Bake or fry them for a satisfying snack or meal. Enjoy the convenience of our premium Fish Sticks.', 4.60, 'fishery13.jpg', 'fishery', 7),
(118, 'Octopus', 'Experience the tender and slightly sweet flavor of our Cleaned Whole Octopus! Looking for a unique and flavorful seafood option? Our Octopus, cleaned and ready to cook, offers a delicate and delicious taste. Grill, braise, or add it to your favorite seafood stews for a culinary adventure. Discover the versatility of our premium Octopus.', 13.70, 'fishery14.jpg', 'fishery', 7),
(119, 'Sea Bass', 'Savor the delicate and flaky texture of our Filleted Sea Bass! Looking for a premium and flavorful fish option? Our Sea Bass, filleted and ready to cook, offers a tender and delicious taste. Bake, grill, or pan-sear it for an elegant and satisfying meal. Elevate your dining experience with our premium Sea Bass.', 10.30, 'fishery15.jpg', 'fishery', 7),
(120, 'Mussels', 'Discover the sweet and savory flavor of our Pack of Black Mussels! Looking for a flavorful and affordable shellfish option? Our Mussels, fresh and ready to cook, offer a delicate and delicious taste. Steam them in white wine, add them to pasta dishes, or create a flavorful seafood stew. Experience the freshness of the sea with our premium Mussels.', 7.10, 'fishery16.jpg', 'fishery', 7),
(121, 'Scallops', 'Indulge in the sweet and delicate flavor of our Large Sea Scallops! Seeking a gourmet seafood treat? Our Scallops, large and succulent, offer a tender and delicious taste. Sear them to perfection for a caramelized and flavorful experience. Treat yourself to the exquisite taste of our premium Scallops.', 12.90, 'fishery17.jpg', 'fishery', 7),
(122, 'Fish Curry Cut', 'Experience the convenience and flavor of our Fish Curry Cut! Looking for the perfect fish for your Indian curries? Our Fish, cut and cleaned for curry, offers a delicious and authentic taste. Cook it with your favorite spices and create a flavorful and aromatic meal. Enjoy the taste of tradition with our premium Fish Curry Cut.', 7.50, 'fishery18.jpg', 'fishery', 7),
(123, 'Mackerel', 'Savor the rich and oily flavor of our Whole Fresh Mackerel! Looking for a healthy and flavorful fish option? Our Mackerel, fresh and whole, offers a distinctive and delicious taste. Grill, bake, or pan-fry it for a nutritious and satisfying meal. Discover the bold flavor of our premium Mackerel.', 6.80, 'fishery19.jpg', 'fishery', 7),
(124, 'Eel', 'Indulge in the delicate and smoky flavor of our Smoked Japanese Eel! Seeking a unique and gourmet seafood experience? Our Eel, smoked to perfection, offers a rich and flavorful taste. Enjoy it in sushi, rice bowls, or as a sophisticated appetizer. Treat yourself to the exquisite taste of our premium Smoked Eel.', 14.60, 'fishery20.jpg', 'fishery', 7),
(125, 'Dish Soap', 'Discover the powerful cleaning action and refreshing scent of our Lemon Fresh Dish Soap! Looking for a reliable and effective dishwashing solution? Our Dish Soap, with its invigorating lemon fragrance, cuts through grease and grime, leaving your dishes sparkling clean. Experience the cleaning power of our premium Dish Soap.', 3.20, 'household1.jpg', 'household', 8),
(126, 'Laundry Detergent', 'Indulge in the stain-fighting power of our 1L Laundry Detergent! Seeking a detergent that tackles tough stains and leaves your clothes fresh? Our Laundry Detergent, with its advanced formula, removes dirt and odors, keeping your laundry clean and vibrant. Experience the superior cleaning performance of our premium Laundry Detergent.', 6.50, 'household2.jpg', 'household', 8),
(127, 'Toilet Paper', 'Savor the soft and gentle comfort of our 4-Roll Pack Toilet Paper! Looking for a reliable and comfortable bathroom essential? Our Toilet Paper, made with soft and absorbent material, provides a gentle and comfortable experience. Choose the quality and comfort of our premium Toilet Paper.', 3.80, 'household3.jpg', 'household', 8),
(128, 'Tissue Box', 'Discover the soft and gentle touch of our Facial Tissues in a Box! Seeking a reliable and soothing tissue for your everyday needs? Our Facial Tissues, made with soft and gentle material, are perfect for colds, allergies, or everyday use. Choose the comfort and quality of our premium Facial Tissues.', 2.60, 'household4.jpg', 'household', 8),
(129, 'Trash Bags', 'Indulge in the strength and reliability of our 30L Black Trash Bags! Looking for durable and leak-proof bags for your waste disposal needs? Our Trash Bags, made with strong and puncture-resistant material, can handle your household waste with ease. Choose the strength and reliability of our premium Trash Bags.', 4.00, 'household5.jpg', 'household', 8),
(130, 'Hand Soap', 'Experience the refreshing and cleansing lather of our Lavender Hand Wash! Seeking a gentle and fragrant hand soap? Our Hand Soap, infused with the calming scent of lavender, cleanses your hands while leaving them feeling soft and refreshed. Choose the gentle and fragrant experience of our premium Hand Soap.', 3.10, 'household6.jpg', 'household', 8);
INSERT INTO `products` (`id`, `name`, `description`, `price`, `image`, `category`, `category_id`) VALUES
(131, 'Bleach', 'Discover the powerful disinfecting action of our 500ml Disinfectant Bleach! Looking for a reliable and effective cleaning solution? Our Bleach, with its strong disinfecting properties, kills germs and bacteria, keeping your surfaces clean and hygienic. Choose the cleaning power of our premium Bleach.', 2.90, 'household7.jpg', 'household', 8),
(132, 'All-purpose Cleaner', 'Indulge in the all-purpose cleaning power of our cleaner that Kills 99.9% of Germs! Seeking a versatile and effective cleaning solution for your entire home? Our All-Purpose Cleaner, with its powerful formula, eliminates dirt, grime, and 99.9% of germs, leaving your surfaces sparkling clean and fresh. Choose the all-in-one cleaning power of our premium All-Purpose Cleaner.', 5.00, 'household8.jpg', 'household', 8),
(133, 'Glass Cleaner', 'Savor the streak-free shine of our Window Spray Glass Cleaner! Looking for a reliable and effective solution for your windows and mirrors? Our Glass Cleaner, with its advanced formula, removes dirt and smudges, leaving your glass surfaces sparkling clean and clear. Experience the clarity and shine of our premium Glass Cleaner.', 4.10, 'household9.jpg', 'household', 8),
(134, 'Toilet Cleaner', 'Discover the powerful cleaning action and fresh scent of our Lemon Scented Toilet Cleaner Liquid! Looking for a reliable and effective solution for your toilet cleaning needs? Our Toilet Cleaner, with its invigorating lemon fragrance, removes stains and eliminates odors, leaving your toilet bowl clean and fresh. Experience the cleaning power of our premium Toilet Cleaner.', 3.70, 'household10.jpg', 'household', 8),
(135, 'Fabric Softener', 'Indulge in the softness and freshness of our Fabric Softener! Seeking a laundry product that makes your clothes feel soft and smell great? Our Fabric Softener, with its gentle formula, reduces wrinkles and static cling, leaving your laundry feeling luxurious. Experience the comfort and freshness of our premium Fabric Softener.', 4.90, 'household11.jpg', 'household', 8),
(136, 'Mop', 'Experience the efficient cleaning power of our Microfiber Floor Mop! Looking for a tool that makes floor cleaning quick and easy? Our Floor Mop, with its microfiber pad, effectively removes dirt and grime from all types of floors. Enjoy a sparkling clean home with our premium Floor Mop.', 7.00, 'household12.jpg', 'household', 8),
(137, 'Broom', 'Discover the reliable cleaning performance of our Indoor Cleaning Broom! Seeking a tool for everyday sweeping and tidying? Our Broom, with its durable bristles, effectively sweeps up dirt and debris from your floors. Keep your home clean and organized with our premium Broom.', 5.50, 'household13.jpg', 'household', 8),
(138, 'Dustpan', 'Savor the convenience and efficiency of our Plastic Dustpan! Looking for a tool to make cleaning up spills and messes easier? Our Dustpan, with its sturdy design, allows you to collect dirt and debris quickly and efficiently. Keep your home tidy with our premium Dustpan.', 2.20, 'household14.jpg', 'household', 8),
(139, 'Sponge Pack', 'Indulge in the scrubbing power of our 5-Pack Kitchen Sponges! Seeking versatile and effective cleaning tools for your kitchen? Our Kitchen Sponges, with their abrasive and absorbent sides, tackle tough messes and leave your dishes sparkling clean. Choose the cleaning power of our premium Kitchen Sponges.', 3.60, 'household15.jpg', 'household', 8),
(140, 'Air Freshener', 'Experience the refreshing and long-lasting fragrance of our Jasmine Room Spray Air Freshener! Looking for a way to create a pleasant and inviting atmosphere in your home? Our Air Freshener, infused with the calming scent of jasmine, eliminates odors and leaves your rooms smelling fresh and clean. Enjoy the ambiance of our premium Air Freshener.', 3.80, 'household16.jpg', 'household', 8),
(141, 'Floor Cleaner', 'Discover the powerful cleaning and disinfecting action of our Pine Disinfectant Floor Cleaner! Looking for a solution that cleans and sanitizes your floors? Our Floor Cleaner, with its refreshing pine scent, removes dirt and kills germs, leaving your floors clean and hygienic. Choose the cleaning power of our premium Floor Cleaner.', 5.25, 'household17.jpg', 'household', 8),
(142, 'Toilet Brush', 'Savor the convenience and hygiene of our Toilet Brush with Holder! Looking for a tool to keep your toilet clean and fresh? Our Toilet Brush, with its sturdy bristles and convenient holder, effectively cleans your toilet bowl. Maintain a clean and hygienic bathroom with our premium Toilet Brush.', 3.40, 'household18.jpg', 'household', 8),
(143, 'Paper Towels', 'Indulge in the absorbency and convenience of our 2 Rolls Pack Paper Towels! Seeking a versatile and reliable cleaning tool for your kitchen? Our Paper Towels, with their absorbent sheets, quickly and effectively clean up spills and messes. Choose the convenience and performance of our premium Paper Towels.', 4.00, 'household19.jpg', 'household', 8),
(144, 'Laundry Basket', 'Experience the durability and practicality of our Vented Plastic Laundry Basket! Looking for a convenient and efficient way to transport your laundry? Our Laundry Basket, with its sturdy construction and vented design, allows for airflow and prevents odors. Make laundry day easier with our premium Laundry Basket.', 6.80, 'household20.jpg', 'household', 8),
(145, 'Frozen Peas', 'Discover the sweet and tender goodness of our Frozen Peas 1kg! Looking for a convenient and nutritious vegetable option? Our Frozen Peas, picked at their peak and frozen to preserve their freshness, are perfect for adding to soups, stews, or as a side dish. Enjoy the vibrant flavor of our premium Frozen Peas.', 4.20, 'frozen1.jpg', 'frozen', 9),
(146, 'Frozen Corn', 'Indulge in the sweet and juicy kernels of our Frozen Corn! Seeking a versatile and easy-to-use vegetable? Our Frozen Corn, with its vibrant yellow color and sweet flavor, is perfect for adding to salads, stir-fries, or enjoying as a side dish. Savor the taste of summer with our premium Frozen Corn.', 3.60, 'frozen2.jpg', 'frozen', 9),
(147, 'Frozen Pizza', 'Experience the cheesy and convenient delight of our 4-Cheese Frozen Pizza! Looking for a quick and satisfying meal? Our Frozen Pizza, topped with a delicious blend of four cheeses, offers a classic and comforting flavor. Bake it to perfection for a delicious and easy dinner. Enjoy the convenience of our premium Frozen Pizza.', 7.50, 'frozen3.jpg', 'frozen', 9),
(148, 'Ice Cream Vanilla', 'Savor the creamy and classic sweetness of our 1L Vanilla Tub Ice Cream! Looking for a timeless and refreshing dessert? Our Vanilla Ice Cream, made with rich and creamy ingredients, offers a smooth and satisfying flavor. Enjoy it on its own, with toppings, or in your favorite desserts. Treat yourself to the classic delight of our premium Vanilla Ice Cream.', 6.00, 'frozen4.jpg', 'frozen', 9),
(149, 'Frozen Fries', 'Discover the crispy and golden goodness of our 1kg Potato Fries! Seeking a classic and satisfying side dish? Our Frozen Fries, made from high-quality potatoes, offer a crispy exterior and a fluffy interior. Bake or fry them to perfection for a delicious addition to any meal. Enjoy the classic taste of our premium Frozen Fries.', 5.40, 'frozen5.jpg', 'frozen', 9),
(150, 'Frozen Chicken', 'Indulge in the flavorful and convenient delight of our Marinated Frozen Chicken Wings! Looking for a quick and easy appetizer or snack? Our Frozen Chicken Wings, marinated for a delicious flavor, are perfect for baking or frying. Enjoy their crispy texture and savory taste. Savor the convenience of our premium Frozen Chicken Wings.', 8.00, 'frozen6.jpg', 'frozen', 9),
(151, 'Frozen Mixed Veg', 'Experience the colorful and nutritious variety of our Mixed Frozen Vegetables! Seeking a convenient and healthy way to add vegetables to your meals? Our Frozen Mixed Vegetables, a blend of various vegetables, offer a diverse range of flavors and nutrients. Use them in stir-fries, soups, or as a side dish. Enjoy the convenience of our premium Frozen Mixed Vegetables.', 4.80, 'frozen7.jpg', 'frozen', 9),
(152, 'Frozen Berries', 'Savor the sweet and tangy burst of flavor in our Frozen Berry Mix Pack! Looking for a versatile and healthy fruit option? Our Frozen Berries, a mix of various berries, are perfect for smoothies, desserts, or enjoying as a refreshing snack. Enjoy the natural sweetness and vibrant colors of our premium Frozen Berries.', 7.00, 'frozen8.jpg', 'frozen', 9),
(153, 'Ice Cubes', 'Discover the convenience and coolness of our Ready-to-Use Ice Cubes! Seeking a quick and easy way to chill your beverages? Our Ice Cubes, frozen and ready to use, are perfect for parties, gatherings, or everyday use. Enjoy the convenience of our premium Ice Cubes.', 2.50, 'frozen9.jpg', 'frozen', 9),
(154, 'Frozen Spring Rolls', 'Indulge in the crispy and savory delight of our Vegetable Spring Rolls! Looking for a delicious and convenient appetizer or snack? Our Frozen Spring Rolls, filled with flavorful vegetables, offer a crispy exterior and a savory interior. Bake or fry them for a quick and satisfying treat. Enjoy the taste of Asia with our premium Frozen Spring Rolls.', 6.30, 'frozen10.jpg', 'frozen', 9),
(155, 'Frozen Lasagna', 'Experience the rich and comforting flavors of our Beef Lasagna Tray! Looking for a satisfying and easy-to-prepare meal? Our Frozen Lasagna, layered with pasta, beef, and cheese, offers a classic Italian dish. Bake it to perfection for a delicious and hearty dinner. Enjoy the convenience of our premium Frozen Lasagna.', 9.50, 'frozen11.jpg', 'frozen', 9),
(156, 'Frozen Broccoli', 'Savor the fresh and vibrant flavor of our Cut Frozen Broccoli Florets! Seeking a convenient and healthy vegetable option? Our Frozen Broccoli, cut into florets and frozen to preserve freshness, is perfect for steaming, roasting, or adding to your favorite dishes. Enjoy the nutritional benefits of our premium Frozen Broccoli.', 3.90, 'frozen12.jpg', 'frozen', 9),
(157, 'Frozen Nuggets', 'Discover the crispy and tender goodness of our Frozen Chicken Nuggets Pack! Looking for a quick and easy meal option for kids and adults alike? Our Frozen Chicken Nuggets, made from high-quality chicken, are perfect for baking or frying. Enjoy their crispy coating and tender interior for a satisfying snack or meal. Enjoy the convenience of our premium Frozen Nuggets.', 6.60, 'frozen13.jpg', 'frozen', 9),
(158, 'Frozen Spinach', 'Indulge in the fresh and leafy goodness of our Chopped Frozen Spinach! Seeking a convenient and nutritious vegetable option? Our Frozen Spinach, chopped and ready to use, is perfect for adding to soups, stews, or pasta dishes. Enjoy the health benefits of spinach in a convenient form with our premium Frozen Spinach.', 3.40, 'frozen14.jpg', 'frozen', 9),
(159, 'Frozen Garlic Bread', 'Experience the savory and aromatic delight of our Garlic Bread Tray! Looking for a quick and easy side dish? Our Frozen Garlic Bread, ready to bake, offers a crispy crust and a flavorful garlic topping. Enjoy it with pasta, salads, or as a delicious appetizer. Savor the convenience of our premium Frozen Garlic Bread.', 4.10, 'frozen15.jpg', 'frozen', 9),
(160, 'Frozen Meatballs', 'Savor the rich and meaty flavor of our Frozen Beef Meatballs! Looking for a versatile and convenient protein option? Our Frozen Meatballs, made from high-quality beef, are perfect for pasta dishes, soups, or appetizers. Cook them to perfection for a delicious and satisfying meal. Enjoy the convenience of our premium Frozen Meatballs.', 7.20, 'frozen16.jpg', 'frozen', 9),
(161, 'Frozen Fish', 'Discover the mild and flaky goodness of our Frozen White Fish Fillets! Seeking a healthy and convenient seafood option? Our Frozen Fish Fillets, ready to cook, offer a delicate flavor that pairs well with various seasonings and cooking methods. Bake, fry, or poach them for a quick and nutritious meal. Enjoy the fresh taste of our premium Frozen Fish.', 8.20, 'frozen17.jpg', 'frozen', 9),
(162, 'Frozen Dumplings', 'Indulge in the flavorful and delicate delight of our Frozen Vegetable Dumplings! Looking for a delicious and convenient Asian-inspired dish? Our Frozen Dumplings, filled with savory vegetables, offer a tender texture and a flavorful filling. Steam, boil, or pan-fry them for a quick and satisfying meal. Enjoy the authentic taste of our premium Frozen Dumplings.', 6.90, 'frozen18.jpg', 'frozen', 9),
(163, 'Frozen Hash Browns', 'Experience the crispy and golden goodness of our Frozen Hash Browns! Looking for a quick and easy breakfast side dish? Our Frozen Hash Browns, made from shredded potatoes, offer a crispy exterior and a fluffy interior. Bake or fry them to perfection for a delicious start to your day. Enjoy the convenience of our premium Frozen Hash Browns.', 5.10, 'frozen19.jpg', 'frozen', 9),
(164, 'Frozen Waffles', 'Savor the sweet and fluffy indulgence of our Sweet Belgian Frozen Waffles! Looking for a delicious and convenient breakfast or dessert? Our Frozen Waffles, with their sweet flavor and fluffy texture, are perfect for topping with your favorite fruits, syrups, or creams. Enjoy a sweet treat with our premium Frozen Waffles.', 4.90, 'frozen20.jpg', 'frozen', 9),
(165, 'Orange Juice', 'Discover the refreshing and tangy taste of our 1L Chilled Orange Juice! Looking for a healthy and delicious way to start your day? Our Orange Juice, made from fresh oranges, is packed with vitamin C and offers a vibrant citrus flavor. Enjoy it as a breakfast beverage, a refreshing drink, or as a base for your smoothies. Start your day with the goodness of our premium Orange Juice.', 3.50, 'beverages1.jpg', 'beverages', 10),
(166, 'Apple Juice', 'Indulge in the sweet and crisp flavor of our Pressed Apple Juice! Seeking a naturally sweet and refreshing beverage? Our Apple Juice, made from fresh apples, offers a pure and delicious taste. Enjoy it chilled as a thirst-quencher, a lunch companion, or as a mixer for your favorite drinks. Savor the natural sweetness of our premium Apple Juice.', 3.30, 'beverages2.jpg', 'beverages', 10),
(167, 'Bottled Water', 'Experience the pure and refreshing hydration of our 500ml Bottled Mineral Water! Looking for a healthy and convenient way to stay hydrated? Our Mineral Water, sourced from natural springs, offers a clean and crisp taste. Carry it with you for a refreshing drink anytime, anywhere. Choose the purity of our premium Bottled Water.', 1.00, 'beverages3.jpg', 'beverages', 10),
(168, 'Sparkling Water', 'Savor the bubbly and refreshing zing of our Sparkling Soda Water Bottle! Seeking a zero-calorie and versatile beverage? Our Sparkling Water, with its crisp bubbles, is perfect for enjoying on its own, adding to juices, or using as a mixer for your favorite cocktails. Add a touch of sparkle to your day with our premium Sparkling Water.', 2.10, 'beverages4.jpg', 'beverages', 10),
(169, 'Coca Cola', 'Indulge in the classic and iconic taste of our 330ml Coca Cola Can! Looking for a refreshing and satisfying soda? Our Coca Cola, with its unique blend of flavors, offers a timeless and enjoyable beverage experience. Enjoy it chilled for a classic treat. Savor the familiar taste of our premium Coca Cola.', 1.50, 'beverages5.jpg', 'beverages', 10),
(170, 'Pepsi', 'Discover the refreshing and bold flavor of our 330ml Pepsi Can! Seeking a classic and satisfying cola? Our Pepsi, with its distinct taste and refreshing bubbles, offers a popular and enjoyable beverage option. Enjoy it chilled for a classic treat. Savor the familiar taste of our premium Pepsi.', 1.50, 'beverages6.jpg', 'beverages', 10),
(171, 'Iced Tea', 'Experience the sweet and refreshing flavor of our Peach Iced Tea! Looking for a cool and flavorful beverage? Our Iced Tea, infused with the sweet taste of peach, offers a refreshing and satisfying drink. Enjoy it chilled for a perfect summer beverage. Quench your thirst with our premium Iced Tea.', 2.80, 'beverages7.jpg', 'beverages', 10),
(172, 'Energy Drink', 'Savor the energizing and invigorating boost of our 250ml Energy Drink Shot! Looking for a quick and convenient way to increase your energy levels? Our Energy Drink, with its blend of caffeine and other energizing ingredients, provides a boost when you need it most. Enjoy it responsibly for a quick pick-me-up. Get energized with our premium Energy Drink.', 3.90, 'beverages8.jpg', 'beverages', 10),
(173, 'Milkshake', 'Indulge in the creamy and chocolatey delight of our Chocolate Flavored Milkshake! Seeking a sweet and satisfying treat? Our Milkshake, with its rich chocolate flavor and creamy texture, offers a delicious and indulgent beverage experience. Treat yourself to the classic taste of our premium Milkshake.', 4.50, 'beverages9.jpg', 'beverages', 10),
(174, 'Smoothie', 'Discover the tropical and fruity blend of our Mango Banana Smoothie! Looking for a healthy and delicious beverage option? Our Smoothie, made with fresh mangoes and bananas, offers a creamy and nutritious drink. Enjoy it as a breakfast, snack, or post-workout beverage. Fuel your body with our premium Smoothie.', 5.10, 'beverages10.jpg', 'beverages', 10),
(175, 'Coffee Can', 'Experience the bold and rich flavor of our Cold Brew Coffee Can! Looking for a smooth and less acidic coffee option? Our Cold Brew Coffee, brewed slowly for a rich taste, offers a refreshing and invigorating beverage. Enjoy it chilled for a smooth coffee experience. Savor the bold flavor of our premium Cold Brew Coffee.', 4.00, 'beverages11.jpg', 'beverages', 10),
(176, 'Green Tea', 'Savor the delicate and refreshing taste of our Organic Green Tea! Looking for a healthy and antioxidant-rich beverage? Our Green Tea, made from organic tea leaves, offers a light and flavorful drink. Enjoy it hot or cold for a soothing and healthy beverage. Choose the natural goodness of our premium Green Tea.', 3.70, 'beverages12.jpg', 'beverages', 10),
(177, 'Black Tea', 'Indulge in the rich and aromatic flavor of our Darjeeling Black Tea! Seeking a classic and flavorful tea experience? Our Black Tea, sourced from the Darjeeling region, offers a distinct and fragrant brew. Enjoy it hot with milk or lemon for a comforting and flavorful beverage. Savor the elegance of our premium Black Tea.', 3.50, 'beverages13.jpg', 'beverages', 10),
(178, 'Herbal Tea', 'Discover the calming and soothing aroma of our Chamomile Herbal Tea Infusion! Looking for a relaxing and caffeine-free beverage? Our Herbal Tea, made from chamomile flowers, offers a gentle and soothing drink. Enjoy it hot before bedtime for a calming experience. Unwind with the tranquility of our premium Herbal Tea.', 4.20, 'beverages14.jpg', 'beverages', 10),
(179, 'Lemonade', 'Experience the tart and refreshing zing of our Fresh Squeezed Lemonade! Looking for a classic and thirst-quenching beverage? Our Lemonade, made from fresh lemons, offers a sweet and tangy drink. Enjoy it chilled on a hot day for a refreshing and revitalizing experience. Quench your thirst with our premium Lemonade.', 2.90, 'beverages15.jpg', 'beverages', 10),
(180, 'Protein Shake', 'Savor the protein-packed and nutritious goodness of our Whey-Based Protein Shake! Looking for a convenient and effective way to support your fitness goals? Our Protein Shake, made with high-quality whey protein, provides essential nutrients for muscle recovery and growth. Enjoy it post-workout or as a meal replacement. Fuel your body with our premium Protein Shake.', 6.00, 'beverages16.jpg', 'beverages', 10),
(181, 'Almond Milk', 'Indulge in the smooth and creamy taste of our Unsweetened Almond Milk 1L! Seeking a dairy-free and low-calorie milk alternative? Our Almond Milk, unsweetened and made from almonds, offers a light and refreshing beverage. Use it in your coffee, cereal, or enjoy it on its own. Choose the healthy and delicious option of our premium Almond Milk.', 4.10, 'beverages17.jpg', 'beverages', 10),
(182, 'Soy Milk', 'Discover the creamy and vanilla-flavored goodness of our Soy Milk! Looking for a dairy-free and plant-based milk alternative? Our Soy Milk, with its smooth texture and vanilla flavor, offers a delicious and nutritious beverage. Use it in your coffee, cereal, or enjoy it on its own. Choose the healthy and flavorful option of our premium Soy Milk.', 3.90, 'beverages18.jpg', 'beverages', 10),
(183, 'Coconut Water', 'Pure coconut water.', 3.80, 'beverages19.jpg', 'beverages', 10),
(184, 'Tonic Water', 'Premium tonic mix.', 2.70, 'beverages20.jpg', 'beverages', 10);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `created_at`) VALUES
(1, 'Wafiq', 'wafiqislam@gmail.com', 'wafiqislam2000', '2025-05-26 08:13:10'),
(2, 'wafiqislam', 'guest@gmail.com', '1234', '2025-05-26 08:22:31');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=185;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
